[TONY-2132] feat: desdription

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,6 +1,6 @@
 #!/bin/sh
-if ! head -1 "$1" | grep -qE "(\[CETE-[0-9]{4}\])( )(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?:.{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid. Format: [CETE-0000] feat: description" >&2
+if ! head -1 "$1" | grep -qE "(\[TONY-[0-9]{4}\])( )(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?:.{1,}$"; then
+    echo "Aborting commit. Your commit message is invalid. Format: [TONY-0000] feat: description" >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
